// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGd73Y48XUy6okg3QXdA8TyWF__odu9s',
    appId: '1:306331853419:web:0e5368342756e11eadc72e',
    messagingSenderId: '306331853419',
    projectId: 'soomuch-a1899',
    authDomain: 'soomuch-a1899.firebaseapp.com',
    storageBucket: 'soomuch-a1899.firebasestorage.app',
    measurementId: 'G-GSEZ7Y6L56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYOfyYJVKPlYEfBgEgRZ7ORwmfDSOR89M',
    appId: '1:306331853419:android:5c074a87ac17917fadc72e',
    messagingSenderId: '306331853419',
    projectId: 'soomuch-a1899',
    storageBucket: 'soomuch-a1899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPbakxo5XOFmyqCqcd8YftBy62PpyX9g',
    appId: '1:306331853419:ios:78b189ae8af0f1e6adc72e',
    messagingSenderId: '306331853419',
    projectId: 'soomuch-a1899',
    storageBucket: 'soomuch-a1899.firebasestorage.app',
    iosBundleId: 'com.example.soomuch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPbakxo5XOFmyqCqcd8YftBy62PpyX9g',
    appId: '1:306331853419:ios:78b189ae8af0f1e6adc72e',
    messagingSenderId: '306331853419',
    projectId: 'soomuch-a1899',
    storageBucket: 'soomuch-a1899.firebasestorage.app',
    iosBundleId: 'com.example.soomuch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdGd73Y48XUy6okg3QXdA8TyWF__odu9s',
    appId: '1:306331853419:web:236768fd04960024adc72e',
    messagingSenderId: '306331853419',
    projectId: 'soomuch-a1899',
    authDomain: 'soomuch-a1899.firebaseapp.com',
    storageBucket: 'soomuch-a1899.firebasestorage.app',
    measurementId: 'G-2B20ESQJQZ',
  );
}
